Remove: Defunct feature flag.
This feature flag no longer appears to exist.  See error message below:

NoMethodError: undefined method `represent_boolean_as_integer=' for nil:NilClass